import { Footer } from './Footer';

export default {
  title: 'Email/Footer',
  component: Footer,
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
  argTypes: {
    logoUrl: { control: 'text', description: 'Primary logo image URL' },
    logoAlt: { control: 'text', description: 'Primary logo alt text' },
    logoLinkUrl: { control: 'text', description: 'Primary logo link URL' },
    secondaryLogoUrl: { control: 'text', description: 'Secondary logo image URL' },
    secondaryLogoAlt: { control: 'text', description: 'Secondary logo alt text' },
    secondaryLogoLinkUrl: { control: 'text', description: 'Secondary logo link URL' },
    disclaimerText: { control: 'text', description: 'Main disclaimer text' },
    additionalText: { control: 'text', description: 'Additional footer text' },
    learnMoreUrl: { control: 'text', description: 'Learn more link URL' },
    learnMoreText: { control: 'text', description: 'Learn more link text' },
    facebookUrl: { control: 'text', description: 'Facebook link URL' },
    twitterUrl: { control: 'text', description: 'Twitter/X link URL' },
    linkedinUrl: { control: 'text', description: 'LinkedIn link URL' },
    unsubscribeUrl: { control: 'text', description: 'Unsubscribe link URL' },
    termsUrl: { control: 'text', description: 'Terms of Use link URL' },
    privacyUrl: { control: 'text', description: 'Privacy Policy link URL' },
    viewInBrowserUrl: { control: 'text', description: 'View in Browser link URL' },
    companyName: { control: 'text', description: 'Company name' },
    companyAddress: { control: 'text', description: 'Company address' },
    copyrightYear: { control: 'text', description: 'Copyright year' },
    backgroundColor: { control: 'color', description: 'Footer background color' },
  },
};

export const Default = {
  args: {
    logoUrl: 'https://img04.en25.com/EloquaImages/clients/PepcoHoldingsInc/%7Bddcc6df9-5abb-40c7-887c-c0f511a4af02%7D_dp_logo_hrz_sm_pos_rgb_g_dm_286.png',
    logoAlt: 'Delmarva Power An Exelon Company logo',
    logoLinkUrl: 'https://www.delmarva.com',
    secondaryLogoUrl: 'https://img04.en25.com/EloquaImages/clients/PepcoHoldingsInc/%7B99bafd08-6966-45ad-9d81-f03b0a6809cc%7D_EmPOWER-MD-logo-final-rgb_g_dm_90.png',
    secondaryLogoAlt: 'Empower Maryland logo',
    secondaryLogoLinkUrl: 'https://energy.maryland.gov',
    disclaimerText: 'Offer valid for Pepco residential customers in Maryland only. Bill credits of up to $26 will be applied monthly for the demand response season from June through October. Customers can opt out of up to two events per season by calling 866-353-5798.',
    additionalText: 'EmPOWER Maryland programs are funded by a charge on your energy bill. EmPOWER programs can help you reduce your energy consumption and save you money.',
    learnMoreUrl: 'https://energy.maryland.gov/pages/facts/empower.aspx',
    learnMoreText: 'here',
    facebookUrl: 'https://facebook.com/delmarvapower',
    twitterUrl: 'https://twitter.com/delmarvapower',
    linkedinUrl: 'https://linkedin.com/company/delmarva-power',
    unsubscribeUrl: 'https://outreach.delmarva.com/PreferenceCenter',
    termsUrl: 'https://www.exeloncorp.com/terms-and-conditions',
    privacyUrl: 'https://www.exeloncorp.com/privacy-policy',
    viewInBrowserUrl: '#',
    companyName: 'Delmarva Power & Light Company',
    companyAddress: '500 N Wakefield Dr., Newark, DE 19702',
    copyrightYear: '2026',
    backgroundColor: '#eeeeee',
  },
};

export const CustomCompany = {
  args: {
    logoUrl: 'https://via.placeholder.com/143x50/14016c/ffffff?text=Logo',
    logoAlt: 'Custom Company Logo',
    logoLinkUrl: 'https://example.com',
    secondaryLogoUrl: 'https://via.placeholder.com/90x50/6e06c1/ffffff?text=Partner',
    secondaryLogoAlt: 'Partner Logo',
    secondaryLogoLinkUrl: 'https://partner.com',
    disclaimerText: 'This is a custom disclaimer for your company. Terms and conditions apply.',
    additionalText: 'Your custom program information goes here.',
    learnMoreUrl: 'https://example.com/learn',
    learnMoreText: 'learn more',
    facebookUrl: 'https://facebook.com',
    twitterUrl: 'https://twitter.com',
    linkedinUrl: 'https://linkedin.com',
    unsubscribeUrl: 'https://example.com/unsubscribe',
    termsUrl: 'https://example.com/terms',
    privacyUrl: 'https://example.com/privacy',
    viewInBrowserUrl: 'https://example.com/view',
    companyName: 'Your Company Name',
    companyAddress: '123 Main Street, City, ST 12345',
    copyrightYear: '2026',
    backgroundColor: '#f5f5f5',
  },
};
